apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: togglemaster
data:
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/650687537445/togglemaster-evaluation-events"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
