apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-aws-sqs
  namespace: togglemaster
spec:
  podIdentity:
    provider: aws
---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: analytics-service
  namespace: togglemaster
spec:
  scaleTargetRef:
    name: analytics-service    
  minReplicaCount: 0            
  maxReplicaCount: 10
  pollingInterval: 20         
  cooldownPeriod: 60      
  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: keda-aws-sqs     
      metadata:       
        queueURL: "https://sqs.us-east-1.amazonaws.com/650687537445/togglemaster-evaluation-events"
        queueLength: "5"      
        awsRegion: "us-east-1"
        identityOwner: operator