apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service
  namespace: togglemaster
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::650687537445:role/role-eks-togglemaster-apps"
