apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: togglemaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: targeting-service
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      containers:
        - name: targeting-service
          image: 650687537445.dkr.ecr.us-east-1.amazonaws.com/togglemaster/targeting-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          env:
            - name: PORT
              value: "8003"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: targeting-service-rds-secret
                  key: DATABASE_URL
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-common
                  key: AUTH_SERVICE_URL
          livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
