apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: targeting-service-rds
  namespace: togglemaster
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: targeting-service-rds-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: togglemaster/rds/targeting
        property: connection_string
