apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-config
  namespace: togglemaster
data:
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/762103020993/togglemaster-evaluation-events"
  REDIS_URL: "set-by-deploy-from-ssm" # Injetado pelo stage de deploy a partir do SSM (/togglemaster/iac/redis-url)
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"
