apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: evaluation-service
  namespace: togglemaster
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: evaluation-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10      # Mantido uma baixa porcentagem baixa para facilitar a demonstração do teste de carga
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0   
      # policies:
      #   - type: Pods
      #     value: 2                     # rampa em degraus: +2 pods a cada 15s
      #     periodSeconds: 15
    # scaleDown:
    #   stabilizationWindowSeconds: 120  # desce devagar (evita flapping na demo)
