apiVersion: v1
kind: ServiceAccount
metadata:
  name: evaluation-service
  namespace: togglemaster
  annotations:
    # ARN da role IRSA criada pelo terraform-consumer (módulo iam-irsa).
    # Também disponível no SSM: /irsa/role-eks-togglemaster-evaluation/role-arn
    # Trust policy: system:serviceaccount:togglemaster:evaluation-service
    eks.amazonaws.com/role-arn: "arn:aws:iam::650687537445:role/role-eks-togglemaster-evaluation"
